repos:
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    sha: v1.0.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]
